### ISSUE TITLE
Button can be quite small

### ISSUE THREAD

**Issue by markulrich** [everydotorg/donate-button#255]
At https://biglittleliferescue.org/donate/ the "Donate Crypto" the button is quite small, why? Do we need size options?

**Comment by santiher** [comment]
The button is small because:

- The html has `font-size: 62.5%`.
- The button `<a>` and `<svg>` font sizes are defined using `rem` which is relative to the html's size.

I couldn't fix the issue by moving from rem to em and setting the button's size to 100%.
The only thing I saw that yields the same results as with html font-size 100%, is using em and adding a font-size of 16px to the button div, but is assuming that the browser's default font is 16px a strong assumption?

**Comment by martinbianchi** [comment]
@santiher we will move the unit from `rem` to `px` to avoid this issue. Also I will add a way to customize the button as we can do with the function `createButton` so we can override the defaults of the button
