### ISSUE TITLE
Docs for deployment to Wordpress

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#47]
Make sure it works well, make clear docs on what to do on `README`

**Comment by martinbianchi** [comment]
@osdiab I added a page to the Wiki about deploying to Wordpress. 
I'm not sure if that step by step will apply for all the sites. My first and unique experience with Wordpress was the Ffungi site implementation and them are using a Theme builder plugin. I based the documentation on what you wrote for Wix and adapt it to the options that I saw on the Ffungi's Wordpress.

I couldn't try to implement it in a new account because you need to have a premum one to be able to add javascript
