### ISSUE TITLE
Make vercel demo use latest version of donate button

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#54]
since I don't have access to the Vercel project, it would be useful to have access to it so that we can inspect what it's showing - can you give us access @jake-nz ?

I assume it's using an old version of the codebase, since it seems to be loading a script called `webComponent.js`, which only shows up in the `every-month` bundle, which I believe is a legacy version of this component. We should make it clearer how the Vercel demo is being served and deployed - it seems to be using `index.html`, but that file has no script tags in it (i think Preact does something magical?), so it's unclear to me what exactly is being rendered. is Vercel hooked up to Git for deploys?

**Comment by jake-nz** [comment]
Vercel was hooked up to the repo as of last week and will update every time there's a push. It's currently out of date because there haven't been any pushes since I connected it.

I've been using https://assets.every.org/donate-button-v2/ as the place to demo and test the latest version. I mainly wanted Vercel so that we could have this functionality for feature branches too.

Unfortunately, with the plan we have, we can't add any more users. We could switch to using your Vercel so that it's all in-house. Otherwise, know that after the next time `main`is updated Vercel will reflect that and continue to.

**Comment by markulrich** [comment]
Can we move the demo to github pages so everything is contained in this repo?

**Comment by jake-nz** [comment]
This is the Github Pages demo: https://assets.every.org/donate-button-v2/
I'm about to submit a PR to update the readme so it reflects the current state (even if we may change it soon). I'll check that it refers to assets.every.org for the demo and not every-month.vercel.app

**Comment by jake-nz** [comment]
Merging #42 has triggered an update to Vercel. From now on every-month.vercel.app will follow `main`
